feature: Course 조회 api
mash-up-kr/piikii_Spring pull request #125
Opened 2024-08-03 12:45 UTC by thguss

## 이슈
closed #68 

## 변경 사항
- api 추가

## 스크린샷

## 부연 설명
- OriginPlace의 Coordinate 타입을 Double로 변경했습니다. TMAP API 테스트 결과 Float 타입으로 요청할 경우 데이터 정합성 문제 가능
- Place 도메인 DTO에 confirmed 필드 추가했습니다.
- schedule 목록 조회 메서드명 변경했습니다.
- 코스 생성 및 조회 api 추가했습니다.
  - 코스 확정 전이라면 투표 결과를 기반으로 장소 확정 후 코스를 조회합니다.
  - confirmed = true 조건에 해당하는 장소로 코스 조합 및 조회합니다.

## 체크리스트

- [ ] Lint 적용 여부
- [ ] 빌드 성공 여부
- [ ] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가
- [ ] PR에 대해 구체적으로 설명이 되어있는가

2024-08-03 12:46 UTC, thguss commented
출격준비

2024-08-04 03:32 UTC, KimDoubleB requested changes
고생하셨습니다.
몇 가지 리뷰 남겨보았어요 :-)
제가 잘 이해못한게 있을 수 있으니 편하게 의견나눠주세요~!

2024-08-04 03:32 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/port/input/dto/response/CourseResponse.kt
> +            placeBySchedule: Map<Schedule, CoursePlace>,
`courseBySchedule`일 것 같습니다. 맞겠죠...?
```suggestion
            courseBySchedule: Map<Schedule, CoursePlace>,
```

이런 네이밍이 조금씩 보이는데 한번 쓱 다 훑어봐주시면 좋을 것 같아요 👍🏻

2024-08-04 03:32 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +        return if (from != null && to != null) {
nullable을 받아서 null check를 안에서 수행해 결과를 반환하는 대신에 메서드 외부에서 null check를 하고 여기는 nullable하지 않게 구성하는게 깔끔할 것 같습니다.

2024-08-04 03:32 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +                place = originPlaceUseCase.getAutoCompleteOriginPlace(place.url),
이거 좀 이상한 것 같아요.
자동완성을 위한 용도의 Client를 Coordinate를 구하기 위해 요청처리하다보면 한번에 요청들이 잔뜩 가게될 것 같고, 응답은 엄청나게 딜레이 될 것 같습빈다.
OriginPlace의 x,y를 Place x,y nullable field를 만들고 넣어두는게 나을 것 같아요.

2024-08-04 03:32 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +                }.second
메서드가 길어지면서 코드의 복잡도가 올라간 느낌입니다 ㅠㅠ
이정도는 메서드로 빼면서 적절한 네이밍으로 구분해보는 것은 어떨까요? 주석을 추가하는 것도 하나의 방법일 것 같아요! (무조건 이대로 메서드로 추출하자는건 아니고 확인해보면서 적절하게 빼보는게 좋을 것 같습니다)

2024-08-04 03:32 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +                .eachCount()
Vote에서도 똑같은 로직이 이용되는데요.
이럴거면 `VoteQueryPort`에서 함수를 만들어 제공하는 것은 어떨까요?

2024-08-04 03:32 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +    private fun confirmPlace(
스케쥴에서 투표가 하나도 되지 않았다면 예외가 발생할 것 같은데요.
이거 혹시 협의가 되었을까요~? 한번 이야기해봐도 좋을 것 같아요 :)

2024-08-04 03:32 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +            .maxWithOrNull(compareBy({ it.second }, { it.first.id }))
2가지 질문이 있습니다.
- vote가 같은 케이스가 있다면 어떻게 되나요?
- 두번째 인자인 `{ it.first.id }`의 의미는 무엇인가요?

2024-08-04 03:32 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/port/output/persistence/SchedulePort.kt
> +    fun findAllByRoomUid(roomUid: UUID): List<Schedule>
👍🏻

2024-08-04 03:32 UTC, KimDoubleB commented on piikii-application/src/test/kotlin/com/piikii/application/domain/course/CourseServiceTest.kt
👍🏻

2024-08-04 03:32 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +        if (!room.isVoteUnavailable()) {
요거 Vote가 아직 시작하지 않은 경우에도 통과할 것 같은데요~!
"마감되었나?"만 확인할 수 있는 함수를 활용하는 것이 좋을 것 같습니다.

2024-08-04 03:32 UTC, KimDoubleB commented on piikii-application/src/test/kotlin/com/piikii/application/domain/course/CourseServiceTest.kt
> +    fun `VoteDeadline 이 현재보다 이후이면 Exception 이 발생한다`() {
`Vote가 시작하지 않은 경우에 Exception이 발생한다.` 테스트도 추가되면 좋을 것 같습니다.

2024-08-04 06:14 UTC, K-Diger reviewed
👍

2024-08-04 06:14 UTC, K-Diger commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +        return if (place.url != null) {
개인적인 취향이 담긴걸수도있는데 개인적으로 null관련 연산할때는 엘비스 연산자 쓰는게 보기 좋았던거같아요

```
place.url?.let { url ->
    Coordinate.from(originPlaceUseCase.getAutoCompleteOriginPlace(url))
}
```

요렇게 해도 되지않을까 싶은데 우선 기능적 문제는 아니니 넘어가도 좋습니다

2024-08-04 06:14 UTC, K-Diger commented on piikii-application/src/test/kotlin/com/piikii/application/domain/course/CourseServiceTest.kt
> +                Place(
[!] 시간 남으면 [!]

이거 픽스쳐 생성하는 메서드나 객체한테 책임 빼는것도 좋아보입니다!

그리고 되도록 객체가 정말 여러개가 필요한 케이스라면 맞지만

굳이 여러개를 검증하지 않아도 된다면 최대한 간결하게 크기를 줄여서 테스트 본문을 가져가는게 좋을 것 같아요

- 단일 객체로 검증가능하면 한 개
- 유즈케이스에 의해 여러 객체가 검증이 필요하면 두 개 ~ 유즈케이스에 필요한 객체 갯수

2024-08-04 06:14 UTC, K-Diger commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +        if (!room.isVoteUnavailable()) {
Super 사소한 의견인데 `!`를 if문에 안넣고 그냥 도메인 메서드 자체에서 저걸 부정하는 로직 + 메서드네이밍을 가져가도 좋을거같아요?!

2024-08-04 06:14 UTC, K-Diger commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +                }.second
동의합니다 주석이나 메서드 캡슐화 해주시면 좀 더 보기 편할것같슴다~

2024-08-04 06:15 UTC, K-Diger commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +            .maxWithOrNull(compareBy({ it.second }, { it.first.id }))
ward

2024-08-04 06:15 UTC, K-Diger commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +    private fun confirmPlace(
ward

2024-08-04 07:01 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/port/input/dto/response/CourseResponse.kt
> +            placeBySchedule: Map<Schedule, CoursePlace>,
앗 이거 Schedule과 대응되는 Place 찾아 매핑한 데이터입니다.
CoursePlace는 코스 후보로 선택된 장소(place) 데이터에요! 장소 내용을 중심으로 담고 있어 placeBySchedule로 명명했습니닷.

2024-08-04 07:38 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +                place = originPlaceUseCase.getAutoCompleteOriginPlace(place.url),
> OriginPlace의 x,y를 Place x,y nullable field를 만들고 넣어두는게 나을 것 같아요.

추가 질문 드립니다! (과도한 요청 및 응답 지연 문제점은 인지했습니당)
x, y 필드를 추가하는 대상이 Entity 맞을까요~? (Place Entity 내에 OriginPlace가 가지는 x, y 필드를 추가하는 것으로 이해했습니다!)

2024-08-04 08:24 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +                .eachCount()
좋습니다. 일단 VoteQueryPort에서 해당 함수를 생성했는데요, 테스트 관련해서 사소한 문제가 있는 것 같아요ㅠㅠ
VoteQueryPort가 모킹으로 지정되다 보니, 해당 로직을 VoteQueryPort에서 제공하면 테스트에서도 똑같은 filtering 로직으로 when-willReturn을 지정해줘야 하긴 하더라구요..? 해당 부분도 생각 중이긴 한데,, 좋은 방법 생각나시면 공유 부탁드려요!

```
        val agreeCountPlaceId =
            votes
                .filter { it.result == VoteResult.AGREE }
                .groupingBy { it.placeId }
                .eachCount()
        given(voteQueryPort.findAgreeCountByPlaceId(votes)).willReturn(agreeCountPlaceId)
```

2024-08-04 08:31 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +    private fun confirmPlace(
앗 고려하지 못했네용! 톡에 물어볼게요~!

2024-08-04 08:36 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +            .maxWithOrNull(compareBy({ it.second }, { it.first.id }))
- vote가 같을 경우 먼저 등록된 장소가 선정됩니다. (디자인팀이랑 합의했어용)
- `it.first.id`는 place의 id 입니닷! maxWithOrNull이 적용되는 대상이 Map<Place, Int> 타입이라 first가 place, second가 Int(count)가 됩니다!

2024-08-04 08:43 UTC, thguss commented
출격준비

2024-08-04 08:46 UTC, thguss commented on piikii-application/src/test/kotlin/com/piikii/application/domain/course/CourseServiceTest.kt
> +                Place(
Fixture와 크기 축소 한번 생각해서 반영해보겠습니당!

2024-08-04 08:55 UTC, thguss commented
특정 스케줄에 포함된 장소 전체를 모두가 반대할 때(찬성 없음), 해당 스케줄은 코스에 포함시키지 않는 것으로 논의 중 👀

2024-08-05 14:24 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/port/input/dto/response/CourseResponse.kt
> +            placeBySchedule: Map<Schedule, CoursePlace>,
아하 이해했습니다. 결국엔 Course에 해당하는 place여서 네이밍이 저거군요~! 👍🏻 
감사합니당ㅎㅎ

2024-08-05 14:26 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +                place = originPlaceUseCase.getAutoCompleteOriginPlace(place.url),
넵넵, 엔티티 말고도 도메인도 포함해서 말한거였습니다.
OriginPlace/OriginPlaceEntity에 있는 longitude, latitude를 Place/PlaceEntity에 추가해야할 것 같고, 그걸 이용해야하는 것이 아닌가? 싶었습니다.

- 이거 앱에 전달 필요 => "자동완성 시, 넘겨주는 longitude, latitude를 장소 생성 시 함께 넘겨주어야 한다."

2024-08-05 14:34 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +            .maxWithOrNull(compareBy({ it.second }, { it.first.id }))
> vote가 같을 경우 먼저 등록된 장소가 선정됩니다. (디자인팀이랑 합의했어용)

에 득표수가 같다면 먼저 등록된 장소가 당첨되는거군요?! ㄷㄷ 몰랐습니다 ㅋㅋ
- 이거 나중에 헷갈리지 않게 해당 로직에 주석으로 추가해두는 것이 좋을 것 같습니다.


> it.first.id는 place의 id 입니닷! maxWithOrNull이 적용되는 대상이 Map<Place, Int> 타입이라 first가 place, second가 Int(count)가 됩니다!

이거 제가 헷갈리는 것일수 있는데요~! 
`maxWithOrNull`이면 최대값 찾을 것 같은데 `compareBy`에서 먼저 등록된 장소가 뽑히기 위해서는 `{it.first.id}`가 들어가는게 맞나요~?

2024-08-05 14:44 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +                .eachCount()
보통 Spy로 주입받거나, 직접 객체를 주입받는 방법도 있는데요.
제 생각엔 해당 기능은 이제 `VoteQueryPort`에 책임이 있으니 관련 기능은 그와 관련된 필터링 기능은 `VoteQueryPort`에서 테스트 코드를 작성하고, Course test에서느 그냥 결과반환 될 응답 fixture(`Map<Long, Int>`)를 직접 선언해서 mocking해도 되지 않나 싶긴 합니다 ㅎㅎ 뭐 지금도 괜찮은 것 같아용

2024-08-05 14:47 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +                place = originPlaceUseCase.getAutoCompleteOriginPlace(place.url),
그리고 이거 Place 내에 longitude, latitude가 들어가면, getCoordinate 함수 자체도 Place 도메인 내부로 들어갈 수 있을 것 같아요~!

2024-08-05 14:50 UTC, KimDoubleB approved these changes
👍🏻

2024-08-05 14:50 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +        val coordinate = getCoordinate(confirmedPlace)
confirmedPlaces 계산하는 로직이 getCoursePlace 안에 있어서 조금 어색한 것 같아요.
confirmedPlaces는 직접 confirm update까지 작업될 수 있는 로직(update)인데, course getter 내부에 있는게 조금 어색한...?
이거 외부에서 confirm place, coordinate 구해서 파라미터로 전달하는 것은 어떨까요~?
(이거 개인적인 의견이에요...!)

2024-08-06 13:03 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +                .eachCount()
오호 좋은 의견 감사합니다! 해당 PR이 좀 커질 것 같아서 VoteQueryPort 테스트 관련 이슈 생성해서 조만간 따로 PR 올려보겠습니당!

2024-08-06 13:04 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +    private fun confirmPlace(
특정 스케줄에 대해서 찬성 표를 받은 장소가 없을 시 스케줄 생략으로 의논했습니다!

2024-08-06 13:11 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/course/CourseService.kt
> +            .maxWithOrNull(compareBy({ it.second }, { it.first.id }))
오 날카로운 지적 감사합니다! id는 오름차순으로 변경해둘게요 ㅎㅎ

2024-08-06 13:12 UTC, thguss commented on piikii-application/src/test/kotlin/com/piikii/application/domain/course/CourseServiceTest.kt
> +                Place(
++의견 감사합니당! PR이 좀 커지고 있어서, 의견 주신 부분 이슈로 따로 추가해서, 별도 PR로 올려보겠습니닷!

2024-08-06 13:31 UTC, thguss commented
출격준비

2024-08-06 15:48 UTC, KimDoubleB approved these changes
👍🏻 👍🏻

2024-08-07 02:53 UTC, thguss commented
반영 전 리뷰는 이슈 따로 파놓아서 해당 PR은 우선 머지 진행하겠습니다!

2024-08-07 02:53 UTC, merged