[ADD] Redis 캐시 도입
mash-up-kr/piikii_Spring pull request #168
Opened 2024-08-22 12:51 UTC by thguss

## 이슈
closed #67 

## 변경 사항
- Redis Cache를 추가했습니다.
- 활용하여 Tmap에서 조회하는 Distance 정보를 캐싱했습니다.

## 스크린샷

## 부연 설명

## 체크리스트

- [ ] Lint 적용 여부
- [ ] 빌드 성공 여부
- [ ] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가
- [ ] PR에 대해 구체적으로 설명이 되어있는가

2024-08-22 12:51 UTC, thguss commented
출격준비

2024-08-23 15:15 UTC, KimDoubleB requested changes
👍🏻 조금 리뷰가 많아졌는데, 시간될 때 확인 부탁드립니당

2024-08-23 15:15 UTC, KimDoubleB commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/config/RedisConfig.kt
> +    private val redisPassword: String? = null
ConfigurationProperties로 구성하면 nullable 안해도 되서 이쁘게 될 것 같은데요!?

2024-08-23 15:15 UTC, KimDoubleB commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/config/RedisConfig.kt
> +        redisConfig.password = RedisPassword.of(redisPassword)
kotlin `apply` 같은걸 활용해서 설정하는 부분을 apply scope으로 넘길 수 있을 것 같아요.

2024-08-23 15:15 UTC, KimDoubleB commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/config/RedisCacheConfig.kt
> +class RedisCacheConfig {
`RedisConfig`와 나눠놓은 이유가 있을까요~?

2024-08-23 15:15 UTC, KimDoubleB commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/adapter/CourseRedisCacheAdapter.kt
> +        endPlace: Place,
2가지 질문이 있습니다.
- 이전 작업이긴한데, 둘의 클래스가 다른 이유가 있나요? 둘 다 `CoursePlace`, `Place` 하나로 통일되지 않은 이유...?
- nullable하면 그냥 앞단에서 다 처리하도록 처리하고, nullable하지 않은 경우만 해당함수가 호출되도록 하는 편이 코드가 훨씬 깔끔해질 것 같습니다.

2024-08-23 15:15 UTC, KimDoubleB commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/adapter/CourseRedisCacheAdapter.kt
> +        }
`let`, `apply`, `run` 등 kotlin scope functions는 사용할 때 주의해야하는 것이 가독성을 해칠 수 있다는 것인데요. 이렇게 활용하면 코드가 한 눈에 안들어오는 것 같습니다.
결국엔 시작 좌표와 마지막 좌표를 구해서 거리를 구하고 싶은 것인데, scope function 없이 그것만 잘 표현하는 것이 어떨까요? (추가로 앞 리뷰에서 nullable한 값으로 넘어오지 않는다면 더 이쁘게 짤 수 있을 것 같음)

```
같은 scope에서
- startPlace coordinate 좌표 확인
- endPlace coordinate 좌표 확인
- getDistance 구함
```

2024-08-23 15:15 UTC, KimDoubleB commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/adapter/CourseRedisCacheAdapter.kt
> +class CourseRedisCacheAdapter(
이거 근데 CourseService에 있어도 되지 않나요?
어차피 `Cacheable` annotation으로 spring boot에서 redis를 이용해 caching처리해주는건데 redis 내부에 구현체가 있어야 하는 이유를 잘 모르겠어서 질문드립니당

2024-08-23 15:15 UTC, KimDoubleB commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/adapter/CourseRedisCacheAdapter.kt
> +        unless = "#result == null",
value, cacheManager는 명시하지 않아도 되지 않을까요? (애매해서 질문드립니당)
- value: 입력안하면 결과로 바로 cache되지 않나요?
- cacheManager: 우린 어차피 cacheManager bean이 하나여서 별다른 지정없어도 되는 것으로 알고 있씀.

2024-08-24 11:47 UTC, thguss commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/config/RedisConfig.kt
> +    private val redisPassword: String? = null
오호 WebLoggerConfig 참고해서

```
class RedisConfig(
    @Value("\${redis.host}")
    private val redisHost: String,
    @Value("\${redis.port}")
    private val redisPort: Int,
    @Value("\${redis.password}")
    private val redisPassword: String
) {
```

이렇게 구성해보았는데 제가 리뷰를 잘 이해한 게 맞을까요!?

2024-08-24 11:50 UTC, thguss commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/config/RedisCacheConfig.kt
> +class RedisCacheConfig {
헉 레퍼런스 참고하다보니 같은 구조로 구성해버렸네요..! 리뷰 감사합니당 :)

2024-08-24 13:45 UTC, thguss commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/adapter/CourseRedisCacheAdapter.kt
> +        endPlace: Place,
> 이전 작업이긴한데, 둘의 클래스가 다른 이유가 있나요? 둘 다 CoursePlace, Place 하나로 통일되지 않은 이유...?

좋은 리뷰 감사해요! 기존 코드에 타입 통일로 반영하여 가독성 면을 보완해보았습니다.
++이전에 살짝 정줄 놓고 짠 코드라 가독성이 많이 훼손되었었네요 🥹 항상 꼼꼼하게 리뷰 남겨주셔서 진심으로 감사드립니당,, 👍👍

<br/>

> nullable하면 그냥 앞단에서 다 처리하도록 처리하고, nullable하지 않은 경우만 해당함수가 호출되도록 하는 편이 코드가 훨씬 깔끔해질 것 같습니다.

이해 완료! 완전 동의!

2024-08-24 14:29 UTC, thguss commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/adapter/CourseRedisCacheAdapter.kt
> +class CourseRedisCacheAdapter(
`Cacheable` annotation 이 cache 모듈에서만 적용 가능한 줄 알았어요🥹  (머쓱,, 도현오빠한테 물어봐서 바로 깨달음)

++같은 클래스 안에서 Cacheable 메서드를 호출하면 설정 부분이 복잡해져서 TmapAdapter 메서드 쪽으로 어노테이션 옮기고 가독성 좀 더 신경써봤습니다!!

2024-08-24 14:32 UTC, thguss commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/adapter/CourseRedisCacheAdapter.kt
> +        unless = "#result == null",
- 엇 맞아요! value 옵션 붙이면 `Distances:id1_id2` 요런 형식으로 캐싱되더라구요!
키 이름을 좀 더 명확히 하고, 이후 다른 키 값을 다른 메서드에서 사용할 때 이름이 겹치지 않게 하는 등 확장성이 더 좋다고 생각하여 value 옵션을 추가했는데, value 없이 바로 추가하는 게 좋을까요?-? 잘 몰라서 물어봅니당~!!

- cacheManager은 하나 밖에 없어서 지워도 좋을 것 같아용 ㅎ.ㅎ

2024-08-26 15:03 UTC, K-Diger approved these changes
고생하셨습니다~ 리뷰 스윽 훑어봐주십쇼!

2024-08-26 15:03 UTC, K-Diger commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/config/RedisConfig.kt
> +    private val redisPassword: String? = null
어 그 방향보다는 아래같은걸로 말씀하신거같아요~

```
@ConfigurationProperties(prefix = "lemon")
data class LemonProperties(
    val url: LemonUrl,
)

data class LemonUrl(
    val regex: Regex,
    val api: String,
) {
    data class Regex(
        val web: String,
        val mobileWeb: String,
        val mobileApp: String,
    )
}
```

2024-08-26 15:03 UTC, K-Diger commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/config/RedisConfig.kt
>          return JsonMapper.builder()
이거 여기선(리뷰 화면) 안보이는데 실제 파일들어가보니까 이것저것 Jackson설정 해주신거같아서...

혹시 저 설정으로 스프링이 기본으로 제공하는 `objectMapper`를 덮어써서 발생할 이슈는 없겠...죠,,?

2024-08-26 15:03 UTC, K-Diger commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/config/RedisConfig.kt
> +    fun redisTemplate(): RedisTemplate<String, Any> {
이거 Value타입을 EventBroker Port에 있는 Event처럼 추상화해도 좋을거같긴한데 혹은 타입을 제한하기 위해 제네릭으로 대체하는 등... 우선 넘어가도 좋습니다~

2024-08-26 15:08 UTC, K-Diger commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/adapter/CourseRedisCacheAdapter.kt
> +        unless = "#result == null",
어 요거 진짜 몰라서 그러는데 condition vs unless가 무슨차이가 있나유?

2024-08-27 06:57 UTC, thguss commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/adapter/CourseRedisCacheAdapter.kt
> +        unless = "#result == null",
@K-Diger 똑같은 것 같아요 🥹

- condition: 캐시 저장되는 조건
- unless: 캐시 저장되면 안되는 조건

2024-08-27 07:00 UTC, thguss commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/config/RedisConfig.kt
>          return JsonMapper.builder()
핫 발생할 이슈가 떠오르지 않긴 하는데..!!
혹시 모르니 ObjectMapper 빈 삭제하고 기본 ObjectMapper()로 설정해둘까요~?

2024-08-27 09:04 UTC, KimDoubleB commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/config/RedisConfig.kt
> +    private val redisPassword: String? = null
도현이 리뷰가 맞습니다...!
Value annotation은 요즘 많이 활용하지 않는 방식 같습니다. (OOP 관점에서)

2024-08-27 09:05 UTC, KimDoubleB commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/config/RedisConfig.kt
>          return JsonMapper.builder()
아니면 기본 제공되는 ObjectMapper bean으로 처리해보고 이상있는지 보는 것은 어떨까요?

2024-08-27 09:07 UTC, KimDoubleB commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/adapter/CourseRedisCacheAdapter.kt
> +        unless = "#result == null",
아하 value가 그 용도군요...? 일단 고고 하시죠 ㅎㅎ

2024-08-27 16:04 UTC, thguss commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/config/RedisConfig.kt
> +    private val redisPassword: String? = null
아아아 또 하나 이렇게 배워갑니다 선생님덜

2024-08-27 16:08 UTC, thguss commented on piikii-output-cache/redis/src/main/kotlin/com/piikii/output/redis/config/RedisConfig.kt
>          return JsonMapper.builder()
제거하고 테스트해보니 이상 없습니닷! 제거해서 다시 push 올릴게요 :)

2024-08-27 16:15 UTC, thguss commented
출격준비

2024-08-29 14:22 UTC, KimDoubleB approved these changes
고생하셨습니다 👍🏻

2024-08-29 14:22 UTC, KimDoubleB commented on piikii-output-web/tmap/src/main/kotlin/com/piikii/output/web/tmap/adapter/TmapNavigationAdapter.kt
> +            ?: Distance.EMPTY
(개인적인 의견, 수정안해도 됩니다)
저는 아래와 같이 코드 작성하는게 가독성 측면에서 좋아보이더라구요.
굳이 scope function을 사용하지 않아도 될 것 같은...? (더 이해하기 어려운)

```kotlin
   return if (startCoordinate != null && endCoordinate != null &&
               startCoordinate.isValid() && endCoordinate.isValid()) {
        getDistanceFromTmap(startCoordinate, endCoordinate)
    } else {
        Distance.EMPTY
    }
```

2024-08-29 16:52 UTC, thguss commented on piikii-output-web/tmap/src/main/kotlin/com/piikii/output/web/tmap/adapter/TmapNavigationAdapter.kt
> +            ?: Distance.EMPTY
오홍 제안해주신 코드가 좀 더 눈에 바로 들어오긴 하네요!
공감해서 반영하도록 하고 머지하도록 할게요~

2024-08-29 16:53 UTC, thguss commented
출격준비

2024-08-29 16:55 UTC, merged