feat: 도메인 초기화
mash-up-kr/piikii_Spring pull request #19
Opened 2024-06-03 14:07 UTC by K-Diger

## 이슈

#18 에 따라 도메인을 정의합니다.

## 변경 사항

- JPA Entity, Repository 추가
- DDL 추가
- 테스트용 Endpoint 추가

- persistence 모듈 내 application.yml 오타 수정

## 스크린샷

## 부연 설명

## 체크리스트

- [x] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가
- [x] PR에 대해 구체적으로 설명이 되어있는가

2024-06-03 15:56 UTC, thguss reviewed
감사합니다~
전체적으로 훑어보고 개인적으로 궁금한 부분은 리뷰로 남겨보았습니다!
내일 중으로 한 번 꼼꼼하게 다시 보고 추가 리뷰 남겨보겠습니당!
수고하셨습니다 정말루~~ 👍 👍 👍

추가로, JPA에서 설정파일(application.yml)에서 `ddl-auto`을 통해 테이블을 자동으로 구성해주는 기능이 있는 것으로 알고있는데, V1.sql 파일을 별도로 사용한 이유가 궁금해요!

2024-06-03 15:56 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/model/SourcePlace.kt
> +    val source: String? = null
source 값은 [enum 클래스로 관리](https://velog.io/@calaf/JPA-%EC%97%94%ED%8B%B0%ED%8B%B0%EC%97%90%EC%84%9C-Enum%EC%9D%84-%EB%8D%94-%EC%9C%A0%EC%97%B0%ED%95%98%EA%B2%8C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95-Converter)해도 좋을 것 같은데 혹시 어떤가요??

2024-06-03 15:56 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/port/output/persistence/SourcePlacePort.kt
> +interface SourceQueryPort {
SourcePlaceQueryPort가 되어야 할 것 같습니당! (Place 빠짐)

2024-06-03 15:56 UTC, thguss commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/adapter/room/RoomCommandAdapter.kt
> +class RoomCommandAdapter(
여기는 `@Transactional` 어노테이션 추가해주지 않아도 되나요!?

2024-06-05 04:03 UTC, KimDoubleB requested changes

2024-06-05 04:03 UTC, KimDoubleB commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/embeded/ThumbnailLink.kt
> +    constructor(contents: List<String>?) : this(contents?.joinToString(","))
이런 패턴들이 조금 많이 보이는 것 같은데, 한 곳에 뭉쳐서 작동할 수 있게 구현하는 것은 어떨까요?
`","`도 많이쓰인다면 상수로 빼도 좋을 것 같습니다.

2024-06-05 12:44 UTC, K-Diger commented
> 감사합니다~ 전체적으로 훑어보고 개인적으로 궁금한 부분은 리뷰로 남겨보았습니다! 내일 중으로 한 번 꼼꼼하게 다시 보고 추가 리뷰 남겨보겠습니당! 수고하셨습니다 정말루~~ 👍 👍 👍
> 
> 추가로, JPA에서 설정파일(application.yml)에서 `ddl-auto`을 통해 테이블을 자동으로 구성해주는 기능이 있는 것으로 알고있는데, V1.sql 파일을 별도로 사용한 이유가 궁금해요!

[Hibernate가 만들어주는 DDL은 운영 환경에 적합하진 않다고 해서 직접 DDL을 관리하는걸로 해봤습니다~](https://docs.jboss.org/hibernate/orm/6.5/userguide/html_single/Hibernate_User_Guide.html#best-practices)

물론 로컬 환경에서는 큰 상관없겠으나... 외부 요소는 운영환경과 동일한 조건으로 가져가보면 좋을 것 같았어요~

2024-06-05 13:22 UTC, K-Diger commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/embeded/ThumbnailLink.kt
> +    constructor(contents: List<String>?) : this(contents?.joinToString(","))
이 리뷰 이해를 못했읍니다 선생님,,,, 부연설명 부탁드립니다.........

2024-06-05 13:37 UTC, K-Diger commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/SourcePlaceEntity.kt
> +        fun SourcePlaceEntity.toVO(sourcePlaceEntity: SourcePlaceEntity): SourcePlace {
companion object를 해제하고 사용하면 아래와 같이 구성되는데 더 좋은 방법이 있을까용



```kotlin
@Repository
@Transactional(readOnly = true)
class SourcePlaceAdapter(
    private val sourcePlaceRepository: SourcePlaceRepository
) : SourcePlaceCommandPort, SourcePlaceQueryPort {

    @Transactional
    override fun save(sourcePlace: SourcePlace): SourcePlace {
        val sourcePlaceEntity = sourcePlace.toEntity()
        sourcePlaceRepository.save(sourcePlaceEntity)
        return sourcePlaceEntity.toDomain(sourcePlaceEntity)
    }

    // null 체크 후 get한 후에 매개변수로 다시 get 해서 넣어주는.... 뭔가 이상한거같은 느낌...?
    override fun retrieve(id: Long): SourcePlace {
        val sourcePlaceEntity = sourcePlaceRepository.findById(id)
        if (sourcePlaceEntity.isPresent) {
            return sourcePlaceEntity.get().toDomain(sourcePlaceEntity.get())
        }
        // TODO 예외 정의
        throw EntityNotFoundException()
    }

    override fun retrieveAll(ids: List<Long>): List<SourcePlace> {
        TODO("Not yet implemented")
    }
}
```

2024-06-06 03:48 UTC, KimDoubleB approved these changes
리뷰반영 아주 럭키비키감사땡큐합니다 👍🏻 
몇 가지 더 있어서 한번 적어보았습니다.

2024-06-06 03:48 UTC, KimDoubleB commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/embeded/ThumbnailLink.kt
> +        if (index >= 0 && index < contentList.size) {
index가 size에 맞는 것인지 validation 하는 것 같은데요.
`deleteWithIndex`와 중복되어 사용되기도 하고, 적절한 네이밍을 갖는 메서드로 빼내면 좋을 것 같습니다 :-)

2024-06-06 03:48 UTC, KimDoubleB commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/embeded/ThumbnailLink.kt
> +    constructor(contents: List<String>?) : this(contents?.joinToString(","))
아아 이거 그냥 계속 String <-> List 왔다갔다하길래... 
혹시 이거 JPA 단에서 Array는 지원안하나? 사용할 때 계속 List로 만들어서 활용하는 것 같은데?!

https://shanepark.tistory.com/484

2024-06-06 03:50 UTC, KimDoubleB commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/embeded/ThumbnailLink.kt
> +    constructor(contents: List<String>?) : this(contents?.joinToString(","))
아 이거 생각해보니 아예 테이블 빼놓고 활용하는거라(정규화/Embeddable) 이렇게 활용하고 있는거군...
이거 혹시 postgresql Array로 저장하는 방안은 어떨까?

근데 이거 PR이 커질수도 있을 것 같아서 보고 내가 작업해볼게

2024-06-06 12:14 UTC, K-Diger commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/embeded/ThumbnailLink.kt
> +    constructor(contents: List<String>?) : this(contents?.joinToString(","))
오케이~~ 확인이요~~

`postgresql Array`이거 써보려했는데 생각보다 쉽지않아서 대충 때려박아부렀네 하하;;

2024-06-06 12:18 UTC, merged