feat : 방 만들기 CRUD 기능 초기 구현
mash-up-kr/piikii_Spring pull request #35
Opened 2024-06-15 15:40 UTC by thguss

for #29 

<br/>

방 만들기 CRUD 기능 1차 구현했습니다.
- 칼럼 변동 가능성을 생각하여, 우선 피그마의 뷰에 나와있는 정보(모임이름`meetingName`, 하고싶은메세지`message`) 위주로 작업했습니다.
- storage 활용이 확정되지 않아 썸네일 관련은 우선적으로 일부 생략습니다.
- dto 타입 변환 및 기능 구현을 위해 일부 nullable 허용했습니다.
- 카테고리는 타플랫폼과 의논 확정되지 않아 우선 생략했습니다.
- 연관관계(ex. 카테고리, 경로 등) 처리를 고민하다가 ERD 변동 가능성을 생각해서 우선 생략했는데, 괜찮을까요?

<br/>

리뷰로 많이 혼내주세요 🥹

2024-06-15 16:22 UTC, K-Diger requested changes

2024-06-15 16:22 UTC, K-Diger commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/RoomEntity.kt
필드는 `val` 키워드로 가져가고 update 구문은 update된 VO를 매개변수로 받는게 좋을 것 같아요

왜냐하면, 지금 `update` 메서드는 [`meetingName`, `message`]만 업데이트 하는 메서드인데, 만약 [ `meetingName`, `message`, `password`] , [`meetingName`, `thumbnailLinks`] 등 여러 필드 조합으로의 경우의 수로 업데이트가 필요하다면 그때마다 메서드를 만드는 것 보단 새로운 업데이트된 객체를 만들고 값 대입해준 후 save()호출하면 모든 경우의 수를 커버칠 수 있을 것 같아서요

2024-06-15 16:22 UTC, K-Diger commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/adapter/room/RoomAdapter.kt
기존 코드의 UseCase 인터페이스는 임시로 메서드를 작성해 놓은거라서 그대로 구현하지 않아도 될 것 같아요

실제 사용자가 유입하는 유즈케이스를 정의해서 구현하는게 어떨까요?

만약 CRUD역할만 하는 서비스를 만들고 싶은 거라면 이 객체 네이밍을 `UseCaseImpl`등으로 바꾸고 CRUD 기능만 수행하는 `Service`객체를 추가하는게 좋아보여요

2024-06-15 16:22 UTC, K-Diger commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/dto/response/RoomGetResponseForm.kt
DTO에서 VO를 통해 response로 변환하는 것도 좋지만 어차피 유즈케이스를 호출하는 것이니까,

유즈케이스에서 컨트롤러가 필요로하는 ResponseDTO를 응답하도록 하면 `Room.toRoomGetResponse()` 이 구문이 없어도 될 것 같아요

아래 리뷰에 남겼지만 UseCase외의 Service 계층을 추가한다면 Service계층에서는 VO를 반환하는게 적절할 것 같지만 유즈케이스는 실제로 컨트롤러가 원하는 DTO를 응답해주는게 어떨까 싶어요

2024-06-15 16:22 UTC, K-Diger commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/RoomApi.kt
> +                message = "방 생성 성공",
응답 객체에 들어갈 `message`필드의 값은 따로 상수 파일에 모아놓고 관리하는 것도 좋을 것 같아요

2024-06-15 16:22 UTC, K-Diger commented on piikii-application/src/main/kotlin/com/piikii/application/port/input/RoomUseCase.kt
아래 리뷰에서 언급했지만 이 메서드들은 임시로 작성해 놓은 거라 컨트롤러 계층에서 바로 쓸 수 있는 유즈케이스를 정의하면 좋을 것 같아요

2024-06-15 16:22 UTC, K-Diger commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/dto/request/RoomSaveRequestForm.kt
> +    private val meetingName: String,
DTO 필드들을 private으로 해두면 유즈케이스에서 DTO 꺼내 쓸 때 필드에 접근을 못할 것 같은데

음... 지금처럼 매번 VO로 변환해서 사용할지는 고민되네요

왜냐하면 사실상 request 받자마자 VO로 변환하기 때문에 VO 자체를 요청값으로 받는 플로우와 다를 것 없어보여서에요

2024-06-15 16:22 UTC, K-Diger commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/RoomApi.kt
> +@RequestMapping("/api/v1/rooms")
사소한거긴 한데 저는 개인적으로 path에 `api`붙이는거 불호라서...

@KimDoubleB 님과 짤막하게 컨벤션 이야기 해볼까요?

2024-06-15 16:22 UTC, K-Diger commented on piikii-application/src/main/kotlin/com/piikii/application/domain/room/Room.kt
음 이거 정말 다 필드들이 Nullable한거에만 반영한건지 검토부탁드립니다.. (지금 졸려서 판단이 안되네요 ,,)

2024-06-15 16:29 UTC, K-Diger commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/RoomEntity.kt
++ 또한 추가된 필드들 DDL에도 업데이트 해주시면 좋을 것 같아요

2024-06-15 16:30 UTC, K-Diger commented
lint관련 커밋은 스쿼시 해도 좋을 것 같습니다

2024-06-16 07:11 UTC, KimDoubleB requested changes
ㅎㅎㅎ 👍🏻 고생하셨습니다
몇 개 리뷰 작성해보았는데요~
저도 잘 모르는 부분일 수 있어서 편하게 대답 부탁드립니다 ㅎㅎㅎ

2024-06-16 07:11 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/room/Room.kt
저도 동일한 리뷰입니다. 코틀린은 Null 열어주는 순간 여러 이점들이 없어져서 활용이 필요한 곳만 열어주는게 좋을 것 같아요.
Response 구현체에서 보면 `!!`가 많은데 Nullable 한 경우 오류를 뿜기때문에, 잘 생각해서 Nullable 한 것만 열어주는게 좋을 것 같습니다.

2024-06-16 07:11 UTC, KimDoubleB commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/RoomApi.kt
> +@RequestMapping("/api/v1/rooms")
전 상관없긴 합니다~ 보통 API 서버 구성시엔 버저닝이랑 같이 작성하기도 했어서...
만약 안하면 그냥 바로 path 작성하는 식? ex) `/rooms`

2024-06-16 07:11 UTC, KimDoubleB commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/dto/response/RoomGetResponseForm.kt
> +fun Room.toRoomGetResponse(): RoomGetResponseForm {
여기서 확장함수보단 `RoomGetResponseForm` 내에 Domain 객체를 받아 `RoomGetResponseForm `를 반환하는 정적 팩토리 생성자 함수를 추가하는 편이 좋아보입니다.
- top level 확장함수 구현 시, 관리가 어려울 수 있어 잘 생각해야한다고 생각함.
- 도메인에서 외부 클래스를 알아가는 함수가 추가되어 관계가 요상해진다고 생각.

2024-06-16 07:11 UTC, KimDoubleB commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/dto/request/RoomUpdateRequestForm.kt
> +    private val message: String?,
둘 다 Nullable 한 값일까요?
meetingName은 안바꾸더라도 클라에서 그대로 받는게 멱등셍있게 구현하기 좋아보여서요.

2024-06-16 07:11 UTC, KimDoubleB commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/RoomApi.kt
> +    ): ResponseEntity<ResponseForm<Any>> {
Any보다는 명확한 반환 클래스를 명시해주는게 좋을 것 같아요 ㅎㅎ

2024-06-16 07:11 UTC, KimDoubleB commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/RoomEntity.kt
>      )
(기존 구현되어있었던 것 같긴한데) 이것도 위에서 이야기 한 것처럼 확장함수말고, RoomEntity에서 Room을 받아 반환하는 정적 함수로 구현하는게 좋아보입니다~!

2024-06-16 07:11 UTC, KimDoubleB commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/RoomEntity.kt
> +    var address: String,
Room Entity 요소들이 var로 바뀐게 좀 있는데, 바꾼 이유가 있을까요~~~?

2024-06-16 07:11 UTC, KimDoubleB commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/dto/response/RoomSaveResponseForm.kt
> +fun Room.toRoomSaveResponse(): RoomSaveResponseForm {
이것도 위 리뷰와 마찬가지 입니다~!

2024-06-16 07:13 UTC, thguss commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/adapter/room/RoomAdapter.kt
이 부분 잘 이해가 안되는데 예시 부탁해도 될까요??

- RoomAdapter 객체를 `RoomUseCaseImpl`와 같은 이름으로 변경
- Service 객체를 추가 (RoomUseCase 대체?)

로 우선 이해를 했어요. RoomService 객체가 있는데 서비스 객체 추가가 어떻게 진행될지 그림이 잘 그려지지 않아요 🥹

2024-06-16 07:38 UTC, thguss commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/RoomApi.kt
> +                message = "방 생성 성공",
오오 상태값으로 고민했었는데 좋아좋아요~!~!

2024-06-16 07:48 UTC, thguss commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/dto/request/RoomSaveRequestForm.kt
> +    private val meetingName: String,
오호.. 바로 변환해버리고 있긴 하네요 🥹
개인적으로는 클라이언트로부터 받아오는 데이터 타입이 기능마다 달라서 Request용 DTO도 필요하다고 생각해요.
유즈케이스 쪽까지 가져가서 변환하는 게 좋을까요 ?-? 고민이군요..🧐

2024-06-16 07:49 UTC, K-Diger commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/adapter/room/RoomAdapter.kt
음 계층형으로 표현하면 아래처럼 구성하는게 어떨까 제안한거였어요

Controller -> Usecase(실제 사용자가 유입되는 유즈케이스) -> Service(특정 도메인에 대한 CRUD 책임만 가진 객체) -> Repository

즉, Usecase는 Service계층에서 수행하는 VO CRUD를 조합해서 하나의 유즈케이스를 만드는 걸 말한거였습니다~

2024-06-16 07:49 UTC, thguss commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/RoomApi.kt
> +@RequestMapping("/api/v1/rooms")
컨벤션 논의 좋아요~~ (추가로 저는 습관으로 붙인거라 어느 방향이든 좋습니다!)

p.s. `api` 붙였을 때 단점이 무엇인가요?-? 불호라니 단순 궁금해져 물어봅니다~~

2024-06-16 07:51 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/room/Room.kt
흠 일단 수정 관련한 뷰가 나오기 전이라 roomId(UUID) 말고는 nullable할 수 없는 필드가 바로 보이진 않네요 🧐
기능 얼추 확정되는대로 바로바로 not null한 필드는 val 처리해두겠슴다 🫡

2024-06-16 07:57 UTC, thguss commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/RoomEntity.kt
> +    var address: String,
update 기능에서 칼럼 값이 변경될 수도 있을 것 같아 우선 roomId(UUID) 제외하고 var로 변경해두었습니다!

2024-06-16 08:02 UTC, K-Diger commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/RoomApi.kt
> +@RequestMapping("/api/v1/rooms")
아 단점이 있어서 그런다기보단 아니라 지극히 개인적인 불호라서 ^^;;

어차피 HTTP API 쏘는건데 굳이 붙이는거 아닌가? 싶었습니당

2024-06-16 08:03 UTC, thguss commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/dto/request/RoomUpdateRequestForm.kt
> +    private val message: String?,
멱등성 있게 받아오는 거 좋네요!
meetingName 타입 변경해두겠습니다~ (와프 보면서 message 값은 optional 필드로 이해했습니다!)

2024-06-16 08:06 UTC, K-Diger commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/dto/request/RoomSaveRequestForm.kt
> +    private val meetingName: String,
맞아요 Request DTO는 있는게 맞는 것 같고

유즈케이스에서 DTO의 데이터를 직접 접근해서 쓸 수 있도록 열어두는게 처리하는데 더 유용하지 않을까 싶습니다~

2024-06-16 08:09 UTC, thguss commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/RoomApi.kt
> +    ): ResponseEntity<ResponseForm<Any>> {
반환할 데이터가 없어서 우선 Any로 지정해뒀는데, 이러한 경우 어떤 클래스를 명시해두는 게 좋을까요!?

2024-06-16 08:57 UTC, KimDoubleB commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/RoomEntity.kt
> +    var address: String,
현재는 변경안하는거면 val로 두는게 어떨까?
나중에 필요할 때 열어주면 될 것 같아서... 이렇게 열어두면 나중에 절대 안닫을거거든. 그러면 변경되는 부분에 있어 추적이 힘들어지기도 하고 사용할 때마다 파악이 필요해서 안좋을 것 같아!

2024-06-16 09:03 UTC, KimDoubleB commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/RoomApi.kt
> +    ): ResponseEntity<ResponseForm<Any>> {
아아 잘못봤다! 데이터가 없군요~

2024-06-16 09:08 UTC, KimDoubleB requested changes

2024-06-16 09:08 UTC, KimDoubleB commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/RoomApi.kt
> +class RoomApi(
`develop` branch rebase 하셔서 ApiDocs도 추가해주시면 좋을 것 같습니다 👍🏻

2024-06-16 10:18 UTC, thguss commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/persistence/entity/RoomEntity.kt
> +    var address: String,
아하 좋아좋아.
그럼 update 기능에 포함되는 필드가 아직 명확하지 않아서, 우선 meetingName이랑 message 정도만 변경 가능으로 열어둘게!

2024-06-16 10:28 UTC, KimDoubleB commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/dto/request/RoomUpdateRequestForm.kt
> +    private val message: String?,
이거 resolve 처리되었는데 수정 안되어있는 것 같습니다. 확인 부탁합니당

2024-06-16 11:03 UTC, thguss commented on piikii-input-http/src/main/kotlin/com/piikii/input/http/controller/room/dto/request/RoomUpdateRequestForm.kt
> +    private val message: String?,
어랏 dto 패키지 옮기고 not null로 고쳐놨는데 아래처럼 안 뜨나용???

![image](https://github.com/mash-up-kr/piikii_Spring/assets/55437339/a220118c-2980-4372-a957-3e3048dd3760)

2024-06-16 14:13 UTC, KimDoubleB approved these changes
빠른 리뷰 반영 감사합니다 👍🏻

2024-06-16 14:13 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/room/Room.kt
> +    val roomId: UUID? = null,
엇 이거 `val`을 말한게 아니라 nullable 옵션(`?`)을 말한거였는데, 한번 더 확인해줄 수 있을까요~?

2024-06-16 14:38 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/room/Room.kt
> +    val roomId: UUID? = null,
헉 바로 고쳐둘게요! 확인확인~

2024-06-17 01:39 UTC, K-Diger approved these changes
👍

2024-06-17 01:39 UTC, K-Diger commented on piikii-output-persistence/postgresql/src/main/kotlin/com/piikii/output/persistence/postgresql/adapter/room/RoomAdapter.kt
> +                ?: throw PiikiiException(ExceptionCode.NOT_FOUNDED)
`detailMessage`필드도 적어주면 좋을 것 같다는 생각입니다!

`detailMessage = "roomId : $id",`

클라한테 예외/에러 메세지로 너무 많은 정보를 내려주는 것도 안좋지만 

그렇다고 너무 적게 주는것도 요청에 대한 문제를 파악하는데 어려움을 주는 것 같다고 생각해서요~

2024-06-17 01:39 UTC, K-Diger commented on piikii-application/src/main/kotlin/com/piikii/application/domain/room/RoomService.kt
>      private val userProducerPort: UserProducerPort,
옴마 이것두 완전 임시로 넣어둔거라서 Producer, Consumer 의존성은 추후에 필요할 때 넣어도 될 것 같아요

2024-06-17 01:39 UTC, K-Diger commented on piikii-application/src/main/kotlin/com/piikii/application/domain/room/RoomService.kt
> +    override fun modifyRoom(
`RoomService`니까 `postfix`에 `Room`은 빼도 될 것 같다는 생각이긴한데

(이건 그냥 취향차이일거 같아서 그냥 넘어가는 것도 상관없을 것 같아요)

2024-06-17 10:34 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/room/RoomService.kt
> +    override fun modifyRoom(
오오 Repository 계층에서도 prefix 안 쓰니까 고렇게 통일해도 좋을 것 같네용!

2024-06-17 10:40 UTC, merged