feat: Add Storage Object Upload
mash-up-kr/piikii_Spring pull request #77
Opened 2024-06-29 19:30 UTC by K-Diger

## 이슈

close #75 

## 변경 사항

- Object Storage 업로드 기능 추가

## 스크린샷

## 부연 설명

## 체크리스트

- [x] Lint 적용 여부
- [x] 빌드 성공 여부
- [x] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가
- [x] PR에 대해 구체적으로 설명이 되어있는가

2024-06-29 19:35 UTC, KimDoubleB commented on piikii-output-objectstorage/build.gradle.kts
> +        implementation("org.glassfish.jaxb:jaxb-runtime:2.3.1")
웁스~

2024-06-29 19:35 UTC, KimDoubleB commented on .github/workflows/config/auto-assign-label-config.yml
> +      - any-glob-to-any-file: [ 'piikii-output-cache/**', 'piikii-output-eventbroker/**', 'piikii-output-persistence/**', 'piikii-output-objectstorage/**']
👍🏻 
그냥 든 생각인데 `objectstorage`보다 `storage`로 모듈명 정하시는건 어떨까요?

2024-06-29 19:36 UTC, KimDoubleB commented on piikii-output-objectstorage/ncp/src/main/kotlin/com/piikii/output/objectstorage/ncp/adapter/NcpObjectStorageAdapter.kt
> +    private val roomFolderName: String,
아 이거 ConfigurationProperty Class로 만들어서 주입받는건 어떨까요~?
Value 너무 보기가 어려워요오~

2024-06-29 19:36 UTC, KimDoubleB requested changes

2024-06-29 19:36 UTC, KimDoubleB commented on piikii-output-persistence/postgresql/src/main/resources/database-config/application-local.yml
> +      ddl-auto: create
`validate` 변경 부탁드립니다.

2024-06-29 19:41 UTC, KimDoubleB commented on piikii-output-objectstorage/ncp/src/main/kotlin/com/piikii/output/objectstorage/ncp/adapter/NcpObjectStorageAdapter.kt
> +        val objectKey = "$folderName/$fileName"
`createObjectKey` method로 빼서 구성해도 좋을 것 같습니다. (함수 이름은 도현씌 마음대로~)

2024-06-29 19:41 UTC, KimDoubleB commented on piikii-output-objectstorage/ncp/src/main/kotlin/com/piikii/output/objectstorage/ncp/adapter/NcpObjectStorageAdapter.kt
> +        val putObjectRequest = PutObjectRequest(bucketName, objectKey, inputStream, objectMetadata)
`createPutObjectRequest` method로 빼서 구성해도 좋을 것 같습니다. (함수 이름은 도현씌 마음대로~)

2024-06-29 20:16 UTC, K-Diger commented
출격준비

2024-06-29 20:22 UTC, thguss approved these changes
📷

2024-06-29 20:22 UTC, thguss commented on piikii-output-storage/build.gradle.kts
> +        // for multipartform
주석 좌표
p.s. 다른 PR에서 주석 삭제하는 diff 종종 봐서 좌표 찍어둡니다~ 의도하신 주석이라면 그대로 고고고

2024-07-01 02:58 UTC, KimDoubleB approved these changes

2024-07-01 02:59 UTC, KimDoubleB commented on piikii-output-storage/ncp/src/main/resources/storage-config/application.yml
> +      name:
이거 name을 빼고 그냥 리스트로 가져가도 되지 않을까 싶긴 합니다 ㅎㅎㅎ

2024-07-01 03:20 UTC, K-Diger commented on piikii-output-storage/build.gradle.kts
> +        // for multipartform
구두로 설명했었나?! 여튼 저 타입 쓸라고 받은 의존성 알려주기 위해서 넣은건데 이따 제거할게요~

2024-07-01 03:20 UTC, K-Diger commented on piikii-output-storage/ncp/src/main/resources/storage-config/application.yml
> +      name:
Roger 집가서 반영하겠읍니다

2024-07-04 10:51 UTC, K-Diger commented on piikii-output-storage/ncp/src/main/resources/storage-config/application.yml
> +      name:
@KimDoubleB 요렇게 의도하신거 맞는지 확인 부탁드려요~

2024-07-04 11:20 UTC, KimDoubleB commented on piikii-output-storage/ncp/src/main/resources/storage-config/application.yml
> +      name:
맞아요오

2024-07-04 11:21 UTC, merged