feat: 방 스케줄 등록 구현
mash-up-kr/piikii_Spring pull request #91
Opened 2024-07-19 06:24 UTC by thguss

## 이슈
closed #87 

## 변경 사항
- 방 스케줄 등록 기능을 구현했습니다. (세부사항 스크린샷 참고)

## 스크린샷

## 부연 설명

## 체크리스트

- [ ] Lint 적용 여부
- [ ] 빌드 성공 여부
- [ ] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가
- [ ] PR에 대해 구체적으로 설명이 되어있는가

2024-07-19 06:25 UTC, thguss commented
출격준비

2024-07-20 13:25 UTC, K-Diger approved these changes
깔끔하네요 고생하셨습니다~

2024-07-21 14:09 UTC, KimDoubleB requested changes

2024-07-21 14:09 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/schedule/ScheduleService.kt
>  @Service
`@Transactional(readOnly = true)` 붙여도 좋을 것 같습니다~

2024-07-21 14:09 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/schedule/ScheduleService.kt
> +        scheduleCommandPort.deleteSchedules(schedulesToDelete.map { it.id!! })
schedules.filter { it.id !in scheduleIdsToRegister }.map
까지 39라인에서 해버리면 될 것 같은데요~

2024-07-21 14:09 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/schedule/ScheduleService.kt
> +        scheduleCommandPort.saveSchedules(schedulesToSave)
이런거 아래와 같이 해볼 수도 있을 것 같아요.
```kotlin
schedulesToRegister
    .filter { it.id == null }
    .let { newSchedules ->
        scheduleCommandPort.saveSchedules(newSchedules)
    }
```

2024-07-21 14:46 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/schedule/ScheduleService.kt
> +        scheduleCommandPort.saveSchedules(schedulesToSave)
오오 새롭게 알아갑니다! 감사해요~~

2024-07-21 14:46 UTC, thguss commented
출격준비

2024-07-21 14:49 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/schedule/ScheduleService.kt
> +        scheduleCommandPort.saveSchedules(schedulesToSave)
> 이런거 아래와 같이 해볼 수도 있을 것 같아요.
> 
> ```kotlin
> schedulesToRegister
>     .filter { it.id == null }
>     .let { newSchedules ->
>         scheduleCommandPort.saveSchedules(newSchedules)
>     }
> ```

제안해준 코드 활용해서, save, update 함수 쪽은 한 줄로 줄일 수 있었어요. 👍 👍 
한 줄로 줄인 코드라 private fun 분리 없애고, register 함수 내부에 포함시켰습니다!
해당 방향 괜찮은지,
delete 함수도 private 풀고 register 함수에 포함시키는 것이 좋을지,
의견 구해봐도 될까요~~??

2024-07-21 14:50 UTC, thguss commented
출격준비

2024-07-21 14:54 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/schedule/ScheduleService.kt
> +            .let { updatedSchedules ->  scheduleCommandPort.updateSchedules(updatedSchedules) }
오 이렇게 보니깐 명확히 로직이 보이네요.
- null이면 추가, 아니면 업데이트.

이렇게 보니 두번 순회를 하게 되는데요.
kotlin의 partition을 이용하면 한번 순회로도 동작할 것 같아요.
```kotlin
schedulesToRegister.partition { it.id == null }.let { (newSchedules, updatedSchedules) ->
    scheduleCommandPort.saveSchedules(newSchedules)
    scheduleCommandPort.updateSchedules(updatedSchedules)
}
```

2024-07-21 14:55 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/schedule/ScheduleService.kt
> +        scheduleCommandPort.deleteSchedules(schedules.filter { it.id !in scheduleIdsToRegister }.map { it.id!! })
앗 이거 제말은 변수 뽑은거에서 map까지 뽑는게 어떨까 싶었습니다.
```suggestion
       val scheduleIdToDelete = schedules.filter { it.id !in scheduleIdsToRegister }.map { it.id!! }
        scheduleCommandPort.deleteSchedules(scheduleIdsToDelete)
```

2024-07-21 14:56 UTC, KimDoubleB commented on piikii-application/src/main/kotlin/com/piikii/application/domain/schedule/ScheduleService.kt
> +        scheduleCommandPort.saveSchedules(schedulesToSave)
아래 코멘트에도 남겼지만, 이 방향도 괜찮을 것 같아요~ 👍🏻 빠른반영 최고~

2024-07-21 14:58 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/schedule/ScheduleService.kt
> +            .let { updatedSchedules ->  scheduleCommandPort.updateSchedules(updatedSchedules) }
세상에나 대박적. 코틀린 만만세 더블비 만만세 👍👍👍👍👍

2024-07-21 15:01 UTC, thguss commented on piikii-application/src/main/kotlin/com/piikii/application/domain/schedule/ScheduleService.kt
> +        scheduleCommandPort.deleteSchedules(schedules.filter { it.id !in scheduleIdsToRegister }.map { it.id!! })
아앗 이해이해!! 친절한 설명 감사해요 🥹

2024-07-21 15:02 UTC, thguss commented
출격준비

2024-07-21 15:58 UTC, KimDoubleB approved these changes
good 💯 
API Test 해보셨겠죠!? 그럼 고고~

2024-07-21 22:20 UTC, merged